import React from "react";
import { Avatar } from "@nextui-org/react";

import { subtitle } from "@/components/primitives";

export default function Home() {
  return (
    <div className="flex w-full flex-col">
      <h2 className={subtitle({ class: "mt-4 font-bold" })}>
        Perfectscale.io Brand
      </h2>
      <span>
        PerfectScale provides DevOps teams with the tools they need to optimize
        Kubernetes environments through easy-to-use solutions that enable quick,
        data-driven decisions. Their platform enhances Kubernetes performance
        and availability while controlling costs, helping companies maintain a
        competitive advantage​
      </span>
      <span className="text-small text-default-500">
        This text was generated by scraping https://perfectscale.io/about and feeding to GenAI for brans summary.
      </span>
      <h2 className={subtitle({ class: "mt-4 font-bold" })}>Competitors</h2>
      <div className="flex w-full flex-row">
        <Avatar
          className="w-10 h-10 text-large mb-4"
          src="https://cast.ai/wp-content/uploads/2023/01/cropped-favicon-1-32x32.png"
        />
        <span className="justify-center ml-4 mt-2">https://cast.ai</span>
      </div>
      <div className="flex w-full flex-row">
        <Avatar
          className="w-10 h-10 text-large"
          src="https://www.kubecost.com/images/favicon.png"
        />
        <span className="justify-center ml-4 mt-2">https://kubecost.com</span>
      </div>
    </div>
  );
}
